---
env:
  pre_settings: []
  modules:
    - { name: 'ymca_demo', status: true }
    - { name: 'ymca_migrate', status: true }
    - { name: 'ymca_migrate_status', status: true }
    - { name: 'devel', status: true }
    - { name: 'config_inspector', status: true }
    - { name: 'config_devel', status: true }
  drush_commands:
    - { name: 'sqlq', status: true, arguments: "--file=./modules/custom/ymca_migrate/misc/legacy.sql" }
    - { name: 'user-password', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'config-set', status: true, arguments: "system.site uuid 97eff2a4-ba00-4bd3-b64c-7641d6ccb54c -y" }
    - { name: 'config-import', status: false, arguments: "staging -y --partial" }
    - { name: 'migrate-import', status: true, arguments: "--group=ymca --force" }
    #- { name: 'search-api-reindex', status: true, arguments: "" }
    #- { name: 'search-api-index', status: true, arguments: "" }
    - { name: 'search-index', status: true, arguments: "" }
  post_settings:
    - { name: '$config_directories["staging"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$settings["cache"]["bins"]["render"]', status: true, value: 'cache.backend.memory' }
    - { name: '$databases["legacy"]["default"]["database"]', status: true, value: '{{ old_source_db_name }}' }
    - { name: '$databases["legacy"]["default"]["username"]', status: true, value: 'root' }
    - { name: '$databases["legacy"]["default"]["password"]', status: true, value: 'root' }
    - { name: '$databases["legacy"]["default"]["host"]', status: true, value: '127.0.0.1' }
    - { name: '$databases["legacy"]["default"]["namespace"]', status: true, value: 'Drupal\\\\Core\\\\Database\\\\Driver\\\\mysql' }
    - { name: '$databases["legacy"]["default"]["driver"]', status: true, value: 'mysql' }