endpoint: 'http://ygtctrain2.personifycloud.com/personifydataservices/PersonifyData.svc/'
username: dmitry.drozdik
password: Helpdesk01
_core:
  default_config_hash: TyAGp6tSkQhv8MYuJvaH7BF1qr7toXeZ0NiU7I3TAcg
